accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='user-profile'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]

blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from blog import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('posts/', include('comments.urls')),
    path('', RedirectView.as_view(url='posts/'))
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

from django.contrib.auth import models as auth_models


class User(auth_models.AbstractUser):
    avatar = models.ImageField(upload_to='avatars', blank=True)
    summary = models.TextField(max_length=2000, blank=True)

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.core.validators import ValidationError

from . import models


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = models.User
        fields = ('username', 'password', 'password2')

    def clean(self):
        super().clean()

        password = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password and password2 and password != password2:
            raise ValidationError('Passwords do not match')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))

        if commit:
            user.save()

        return user


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False)
    summary = forms.CharField(
        max_length=2000, widget=forms.Textarea, required=False)

    class Meta:
        model = models.User
        fields = ('avatar', 'summary')

    def clean(self):
        super().clean()

        avatar = self.cleaned_data.get('avatar')

        # If avatar large then 10mb
        if not avatar and avatar.size > 1024 * 1024 * 10:
            raise ValidationError('large_image')

    def save(self, commit=True):
        user = super().save(commit=False)
        avatar = self.cleaned_data.get('avatar')
        
        # If avatar exist add it
        if avatar:
            user.avatar = avatar

        if commit:
            user.save()

        return user

accounts/views.py
# from django.shortcuts import render
from django.views import generic as generic_views
from django.urls import reverse_lazy

from posts import models as posts_models

from . import models
from . import forms

# Create your views here.


class RegisterView(generic_views.CreateView):
    template_name = 'registration/register.html'
    form_class = forms.RegisterUserForm
    success_url = reverse_lazy('login')


class ProfileView(generic_views.UpdateView):
    template_name = 'profile.html'
    form_class = forms.ProfileForm
    context_object_name = "obj"
    success_url = reverse_lazy('user-profile')

    def get_object(self):
        return self.request.user


class UserProfileView(generic_views.DetailView):
    model = models.User
    context_object_name = "obj"
    template_name = 'user_profile.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['posts'] = posts_models.Post.objects.filter(author=models.User.objects.get(
            id=self.request.resolver_match.kwargs['pk'])).order_by('-created_at')

        return data

accounts/templates/profile.html
{% extends "base.html" %}

{% block head%}

<title>Edit profile</title>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const currentAvatar = document.querySelector('#current_avatar')
    const avatarInp = document.querySelector('#id_avatar')

    avatarInp.addEventListener('change', () => {
      const file = avatarInp.files[0]

      currentAvatar.src = URL.createObjectURL(file)
    })
  })
</script>
{% endblock %}

{% block main %}
<h1 class="text-2xl font-bold text-center">
  Profile {{obj}}
</h1>

<section class="">
  <form action="" class="flex flex-col align-center gap-4" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="flex gap-4">

      {% if obj.avatar %}

      <div class="group relative w-48 h-48 shrink-0">
        <div class="absolute top-0 left-0 w-48 h-48">
          {% if obj.avatar %}
          <img id="current_avatar" class="block rounded-full w-48 h-48" src="{{obj.avatar.url}}" alt="avatar">
          {% endif %}
        </div>


        <div class="absolute top-0 left-0 w-48 h-48 flex items-center justify-center">
          <label for="id_avatar"
            class="invisible group-hover:visible flex opacity-0 group-hover:opacity-100 duration-500 transition-opacity flex-col items-center justify-center w-48 h-48 border-2 border-gray-300 border-dashed rounded-full cursor-pointer bg-gray-50/50 dark:bg-gray-900/50">
            <!-- bg-gray-50 hover:bg-gray-100 -->
            <div class="flex flex-col items-center justify-center pt-5 pb-6">
              <svg class="w-6 h-6 mb-2 text-gray-500 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 20 16">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
              </svg>
              <p class="mb-2 text-center text-sm text-gray-500 dark:text-gray-600 font-semibold">
                Click to upload
              </p>
              <p class="text-xs text-center text-gray-500 dark:text-gray-600">
                SVG, PNG, JPG or GIF
              </p>
            </div>

            <input id="id_avatar" name="avatar" type="file" accept="image/*" class="hidden" />

          </label>
        </div>

      </div>

      {% else %}

      <div class="w-48 h-48 flex items-center justify-center">
        <label for="id_avatar"
            class="flex flex-col items-center justify-center w-48 h-48 border-2 border-gray-300 border-dashed rounded-full cursor-pointer bg-gray-50/50 dark:bg-gray-900/50">
            <!-- bg-gray-50 hover:bg-gray-100 -->
            <div class="flex flex-col items-center justify-center pt-5 pb-6">
              <svg class="w-6 h-6 mb-2 text-gray-500 dark:text-gray-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 20 16">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
              </svg>
              <p class="mb-2 text-center text-sm text-gray-500 dark:text-gray-600 font-semibold">
                Click to upload
              </p>
              <p class="text-xs text-center text-gray-500 dark:text-gray-600">
                SVG, PNG, JPG or GIF
              </p>
            </div>

            <input id="id_avatar" name="avatar" type="file" accept="image/*" class="hidden" />

          </label>
      </div>

      {% endif %}

      <div class="w-full">
        <label for="message" class="block ml-2 mb-2 text-sm font-medium dark:text-white">Summary</label>
        <textarea id="message" rows="4" name="summary" maxlength="2000" id="id_summary"
          class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-500 dark:text-white"
          placeholder="Write your thoughts here...">{{form.summary.value}}</textarea>
      </div>

    </div>

    <button type="submit" class="ml-auto inline-block px-3 py-1.5 font-semibold text-sm bg-primary-500 hover:bg-primary-700 rounded text-white duration transition-colors">
      Save
    </button>
  </form>
</section>
{% endblock %}

accounts/templates/user_profile.html
{% extends "base.html" %}

{% block main %}
<h1 class="text-center font-bold text-2xl">
  Profile {{obj}}
  <a class="text-sm text-blue-500 hover:text-blue-700 underline" href="{% url 'profile' %}">edit</a>
</h1>

<section class="">

  <div class="flex gap-4">
    <div class="shrink-0">
      {% if obj.avatar %}
      <img class="block rounded-full w-32 h-32" src="{{obj.avatar.url}}" alt="avatar">
      {% endif %}
    </div>

    <div class="w-full h-full">
      <p class="h-fit border border-gray-500 rounded-md w-full px-4 py-2 text-sm">
        {% if obj.summary %}
        {{obj.summary}}
        {% else %}
        No summary
        {% endif %}
      </p>
    </div>
  </div>

</section>

<section class="py-4 my-4 flex justify-end border-gray-500 border-t border-b">
  <a class="px-3 py-1.5 font-semibold text-sm bg-primary-500 hover:bg-primary-700 rounded text-white"
    href="{% url 'create-post' %}">
    New post
  </a>
</section>

<section class="">
  <h2 class="text-xl font-bold text-center my-4">
    Posts
  </h2>
  
  {% if posts %}
  
  <div class="grid grid-cols-3 gap-4">
    {% for post in posts %}
  
    <a class="" href="{% url 'detail-post' post.pk %}">
      <div class="border border-gray-500 rounded-md flex flex-col items-center gap-4 p-4">
        {% if post.image %}
        <img src="{{post.image.url}}" class="" alt="img">
        {% endif %}
  
        <p class="w-full">{{post.content}}</p>
      </div>
    </a>
  
    {% endfor %}
  </div>
  
  {% else %}
  <h2 class="my-4 text-center font-bold text-2xl">No posts</h2>
  {% endif %}
</section>

{% endblock %}