blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from blog import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('posts/', include('comments.urls')),
    path('', RedirectView.as_view(url='posts/'))
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:pk>/comment', views.CreateComment.as_view(), name='create-comment'),
    path('<int:post_pk>/comments/<int:pk>/delete', views.DeleteComment.as_view(), name='delete-comment'),
    path('<int:post_pk>/comments/<int:pk>/update', views.UpdateComment.as_view(), name='update-comment'),
]

comments/models.py
from django.db import models
from django.utils.timezone import utc

from datetime import datetime

# Create your models here.


class Comment(models.Model):
    post = models.ForeignKey('posts.Post', on_delete=models.CASCADE, blank=False)
    author = models.ForeignKey('accounts.User', on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='comments', blank=True)
    content = models.CharField(max_length=2000, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def time(self):
        now = datetime.utcnow().replace(tzinfo=utc)

        if (self.updated_at - self.created_at).seconds > 3:
            diff = (now - self.updated_at)
            if diff.days == 0:
                # Today 00:00
                return self.updated_at.strftime('Edited today %H:%M')
            elif diff.days < 7:
                # Monday 00:00
                return self.updated_at.strftime('Edited %A %H:%M')
            elif diff.days < 365:
                # November 1 00:00
                return self.updated_at.strftime('Edited %B %d %H:%M')
            else:
                # 2023 November 1 00:00
                return self.updated_at.strftime('Edited %Y %B %d %H:%M')
        else:
            diff = (now - self.created_at)
            if diff.days == 0:
                # Today 00:00
                return self.created_at.strftime('Today %H:%M')
            elif diff.days < 7:
                # Monday 00:00
                return self.created_at.strftime('%A %H:%M')
            elif diff.days < 365:
                # November 1 00:00
                return self.created_at.strftime('%B %d %H:%M')
            else:
                # 2023 November 1 00:00
                return self.created_at.strftime('%Y %B %d %H:%M')

    def __str__(self) -> str:
        return self.content

    @staticmethod
    def get_comments_by_post(post):
        return Comment.objects.filter(post=post)

comments/forms.py
from django import forms

from posts import models as post_models

from . import models


class CreateCommentForm(forms.ModelForm):
    content = forms.CharField(
        max_length=2000, widget=forms.Textarea, required=True)

    class Meta():
        model = models.Comment
        fields = (
            'content',
            'image',
        )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')

        if self.request is None:
            raise Exception('No request in form')

        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        comment = super().save(commit=False)

        comment.post = post_models.Post.objects.get(
            id=self.request.resolver_match.kwargs['pk'])
        comment.author = self.request.user

        if commit:
            comment.save(True)

        return comment

comments/views.py
from django.urls import reverse_lazy
from django.views import generic as generic_views

from posts import models as post_models

from . import models
from . import forms

# Create your views here.


class CreateComment(generic_views.CreateView):
    form_class = forms.CreateCommentForm
    template_name = 'create_comment.html'

    def get_queryset(self):
        return post_models.Post.objects.get_queryset()

    def get_success_url(self) -> str:
        return reverse_lazy('detail-post', kwargs={'pk': self.request.resolver_match.kwargs['pk']})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs['request'] = self.request

        return kwargs

class DeleteComment(generic_views.DeleteView):
    model = models.Comment
    template_name = 'delete_comment.html'

    def get_success_url(self) -> str:
        return reverse_lazy('detail-post', kwargs={'pk': self.request.resolver_match.kwargs['post_pk']})


class UpdateComment(generic_views.UpdateView):
    model = models.Comment
    fields = ('content', 'image',)
    template_name = 'update_comment.html'

    def get_success_url(self) -> str:
        return reverse_lazy('detail-post', kwargs={'pk': self.request.resolver_match.kwargs['post_pk']})

comments/templates/create_comment.html
{% extends 'base.html' %}

{% block head %}

<title>Create comment</title>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const currentImage = document.querySelector('#current_image')
    const imageInp = document.querySelector('#id_image')
    const inpContainer = document.querySelector('#inp_container')

    imageInp.addEventListener('change', () => {
      const file = imageInp.files[0]

      currentImage.src = URL.createObjectURL(file)
      !inpContainer.classList.contains('opacity-0') && inpContainer.classList.add('opacity-0')
    })
  })
</script>

{% endblock head %}

{% block main %}

  <form action="" method="post" enctype="multipart/form-data" class="space-y-4">

    {% csrf_token %}

    <!--  -->

    <div class="group relative w-full h-64 top-0 left-0">
      <div class="absolute w-full top-0 left-0">
        <img id="current_image" class="mx-auto h-64 block" alt="image">
      </div>
    
      <div id="inp_container" class="absolute group-hover:opacity-100 duration-500 transition-opacity top-0 left-0 w-full flex items-center justify-center">
        <label for="id_image"
          class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
          
          <div class="flex flex-col items-center justify-center pt-5 pb-6">
            <svg class="w-8 h-8 mb-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
              viewBox="0 0 20 16">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
            </svg>
            <p class="mb-2 text-sm text-gray-500 dark:text-gray-400 font-semibold">Click to upload</p>
            <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF</p>
          </div>
        
          <input name="image" id="id_image" type="file" class="hidden" />
        
        </label>
      </div>
    
    </div>

    <!--  -->

    <div class="w-full">
      <label for="id_content" class="block ml-2 mb-2 text-sm font-medium dark:text-white">Summary</label>
      <textarea name="content" rows="4" maxlength="2000" id="id_content"
        class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-500 dark:text-white"
        placeholder="Write your comment here...">{{form.summary.value}}</textarea>
    </div>

    <button type="submit" class="ml-auto block px-3 py-1.5 font-semibold text-sm bg-primary-500 hover:bg-primary-700 rounded text-white">
      Create
    </button>
  </form>

{% endblock %}

comments/templates/delete_comment.html
{% extends 'base.html' %}

{% block head %}

<title>Delete comment</title>

{% endblock head %}

{% block main %}

<form action="" method="post" enctype="multipart/form-data" class="space-y-4">

  {% csrf_token %}

  <h1 class="text-center text-2xl font-bold">
    Confirm comment deletion
  </h1>
  
  <button type="submit"
    class="mx-auto block px-3 py-1.5 font-semibold text-sm bg-primary-500 hover:bg-primary-700 rounded text-white">
    Confirm
  </button>

</form>

{% endblock %}

comments/templates/update_comment.html
{% extends 'base.html' %}

{% block head %}

<title>Update comment</title>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const currentImage = document.querySelector('#current_image')
    const imageInp = document.querySelector('#id_image')

    imageInp.addEventListener('change', () => {
      const file = imageInp.files[0]

      currentImage.src = URL.createObjectURL(file)
    })

    if (currentImage.getAttribute('src')) {
      currentImage.classList.remove('hidden')
    }
  })
</script>

{% endblock head %}

{% block main %}

<form action="" method="post" enctype="multipart/form-data" class="space-y-4">

  {% csrf_token %}

  <!--  -->

  <div class="group relative w-full h-64 top-0 left-0">
    <div class="absolute w-full top-0 left-0">
      {% if form.image.value %}
      <img id="current_image" class="hidden mx-auto h-64 block" src="{{form.image.value.url}}" alt="image">
      {% else %}
      <img id="current_image" class="hidden mx-auto h-64 block" alt="image">
      {% endif %}
    </div>
  
    <div class="absolute opacity-10 group-hover:opacity-100 duration-500 transition-opacity top-0 left-0 w-full flex items-center justify-center">
      <label for="id_image"
        class="flex flex-col items-center justify-center w-full h-64 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600">
  
        <div class="flex flex-col items-center justify-center pt-5 pb-6">
          <svg class="w-8 h-8 mb-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
            viewBox="0 0 20 16">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
          </svg>
          <p class="mb-2 text-sm text-gray-500 dark:text-gray-400 font-semibold">Click to upload</p>
          <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF</p>
        </div>
  
        <input name="image" id="id_image" type="file" class="hidden" />
  
      </label>
    </div>
  
  </div>

  <!--  -->

  <div class="w-full">
    <label for="id_content" class="block ml-2 mb-2 text-sm font-medium dark:text-white">Summary</label>
    <textarea name="content" rows="4" maxlength="2000" id="id_content"
      class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 dark:bg-gray-800 rounded-lg border border-gray-500 dark:text-white"
      placeholder="Write your comment here...">{{form.content.value}}</textarea>
  </div>

  <button type="submit"
    class="ml-auto block px-3 py-1.5 font-semibold text-sm bg-primary-500 hover:bg-primary-700 rounded text-white">
    Update
  </button>
</form>

{% endblock %}